### ISSUE TITLE
When code release?

### ISSUE THREAD

**Issue by Senwang98** [yanglei18/Mix-Teaching#1]
@yanglei18 

Thanks for your amazing work and congratulate to be rank1 of mono3d field now!

I feel confused about data aug in monocular 3d object detections now because I have not figured out how to process bbox gt when copy to another image.
So, I want to know when will the codes open source (Utill AAAI23 deadline?)

wishing for your reply, and good luck to you!

**Comment by yanglei18** [comment]
Thanks for your attention,  code will be organized to release before the end of September.

**Comment by Senwang98** [comment]
@yanglei18 
Fine, got it

**Comment by Senwang98** [comment]
hello, will you release code about GUPNet? maybe you can create one new git branch.

**Comment by Senwang98** [comment]
@yanglei18 
sorry to disturb, the kitti dataset currently cannot be downloaded using `wget`, is there a solution?
