### ISSUE TITLE
geo_conf and geo_conf_threshold

### ISSUE THREAD

**Issue by charmeleonz** [yanglei18/Mix-Teaching#4]
Hi, can you please explain what geo_conf and geo_conf_threshold mean? Thank you.

**Comment by yanglei18** [comment]
1. `geo_conf`  implies `1 - uncertainty`;
2. `geo_conf_threshold` represents the threshold of ` 1 - uncertainty`

**Comment by charmeleonz** [comment]
@yanglei18 Thanks a lot.
